export const GET_GRUMBS = 'GET_GRUMBS'
export const ONE_GRUMB = 'ONE_GRUMB'
export const GET_RESPONSES = 'GET_RESPONSES'
export const GET_VOTE = 'GET_VOTE'
export const GET_VOTES = 'GET_VOTES'
export const CLEAR_GRUMB = 'CLEAR_GRUMB'